version: "3.7"
services:
  backend_service:
    build: ./backend
    ports:
      - 5000:5000
    networks:
      - opcalc-net
    volumes:
      - .m2:/root/.m2
  frontend_service:
    build: ./frontend
    ports:
      - 3000:3000
    environment:
      - REACT_APP_BACKEND_API_URL=$REACT_APP_BACKEND_API_URL
    networks:
      - opcalc-net
    depends_on:
      - backend_service
networks:
  opcalc-net:
