spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  error:
    whitelabel:
      enabled: false
  port: ${SERVER_PORT}

jwt:
  signing-key: ${JWT_SIGNING_KEY}
  expiration-in-ms: ${JWT_EXPIRATION_IN_MS}